# Generated by Django 4.0.5 on 2022-07-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('CPF', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
