# Generated by Django 4.0.5 on 2022-07-08 20:39

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
