# Generated by Django 4.0.5 on 2022-07-05 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('idade', models.IntegerField()),
                ('ch', models.CharField(max_length=10)),
                ('data_curso', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
