# Generated by Django 4.0.5 on 2022-07-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avasus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avasus',
            name='objetivo',
            field=models.TextField(null=True),
        ),
    ]
