# Generated by Django 4.0.5 on 2022-07-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avasus', '0004_avasus_ch_avasus_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='avasus',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
