# Generated by Django 4.0.5 on 2022-07-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avasus', '0005_avasus_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='avasus',
            name='foto_curso',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
